server:
  port: 8085
 
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true  
#spring.main.web-application-type=reactive
spring:
 main:
  web-application-type: reactive
 application:
    name: gateway-service
# cloud:
#  gateway:
#   routes:
#      - id: producer
#        uri: lb://PRODUCER-SERVICE
#        predicates:
#        - Path=/api/v1/pc/**
#      - id: consumer
#        uri: lb://CONSUMER-SERVICE
#        predicates:
#        - Path=/api/v1/cc/**